### ISSUE TITLE
Server side managed loading words

### ISSUE THREAD

**Issue by btakeya** [o-hoo/Around#26]
See: https://github.com/kstreee-around/AroundServer/issues/32

Loading words should be controlled by server side logic.
- Every read APIs accept locale from url query parameters
- Server returns loading message optionally, through the 'meta' property of result json.

**Comment by btakeya** [comment]
Related issue: https://github.com/o-hoo/Around/issues/23

**Comment by kstreee** [comment]
Deprecated issue
