### ISSUE TITLE
null point exception on empty POST request for /api/1.0/crawl

### ISSUE THREAD

**Issue by kstreee** [o-hoo/Around#50]

**Comment by btakeya** [comment]
NPE has occured with _no Content-Type header_ request.
- ex: $ curl -XPOST http://localhost:9000/api/1.0/crawl

@kstreee: is there any request can be without Content-Type header?

**Comment by btakeya** [comment]
Below messages are not about NPE:
- error.BadRequestException: null
- Execution exception[[BadRequestException: null]]

Maybe missing implementation of our custom exception classes.

**Comment by kstreee** [comment]
Resolved by this pull request.
The null pointer exception is caused by throwing exception instead of returning BadRequest object.

https://github.com/kstreee-around/AroundWeb/commit/c388aaf96a0681e06b60f271d493effb3533037e#diff-67b806c708cd61565648429affcf889fL23
