### ISSUE TITLE
Implement FacebookSignIn API in Play

### ISSUE THREAD

**Issue by iandmyhand** [o-hoo/Around#55]
Refer to https://github.com/kstreee-around/AroundServer/blob/master/AroundAPIServer/Controllers/API/AccountAPIController.cs

**Comment by iandmyhand** [comment]
[여기](https://github.com/kstreee-around/AroundServer/blob/master/AroundAPIServer/BizObjects/AccountManager/AccountManager.cs#L65) 옮기다 말았음

**Comment by btakeya** [comment]
merged into o-hoo/Around#56
